[versions]
composeCompiler = "1.5.0"
compose = "1.7.0-beta01"
coil = "2.3.0"
accompanist = "0.24.1-alpha"
androidGradlePlugin = "8.2.2"

[libraries]
androidx-exif = "androidx.exifinterface:exifinterface:1.3.7"
androidx-core-ktx = "androidx.core:core-ktx:1.13.1"
androidx-appcompat = "androidx.appcompat:appcompat:1.6.1"
google-material = "com.google.android.material:material:1.12.0"

androidx-lifecycle-runtime = "androidx.lifecycle:lifecycle-runtime-ktx:2.8.0"
androidx-activity-compose = "androidx.activity:activity-compose:1.9.0"
junit = "junit:junit:4.13.2"
androidx-test-junit = "androidx.test.ext:junit:1.1.5"
androidx-test-espresso = "androidx.test.espresso:espresso-core:3.5.1"

androidx-constraintlayout-compose = "androidx.constraintlayout:constraintlayout-compose:1.0.0-alpha07"
androidx-navigation-compose = "androidx.navigation:navigation-compose:2.7.0"

jvziyaoyao-origeek-ui = "com.github.jvziyaoyao:OrigeekUI:1.0.1-alpha.7"

androidx-compose-ui-util = { group = "androidx.compose.ui", name = "ui-util", version.ref = "compose" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "compose" }
androidx-compose-material = { group = "androidx.compose.material", name = "material", version.ref = "compose" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "compose" }
androidx-compose-ui-test = { group = "androidx.compose.ui", name = "ui-test-junit4", version.ref = "compose" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "compose" }
androidx-compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended", version.ref = "compose" }

coil = { group = "io.coil-kt", name = "coil", version.ref = "coil" }
coil-svg = { group = "io.coil-kt", name = "coil-svg", version.ref = "coil" }
coil-gif = { group = "io.coil-kt", name = "coil-gif", version.ref = "coil" }
coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }

google-accompanist-permissions = { group = "com.google.accompanist", name = "accompanist-permissions", version.ref = "accompanist" }
google-accompanist-systemuicontroller = { group = "com.google.accompanist", name = "accompanist-systemuicontroller", version.ref = "accompanist" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
jetbrains-kotlin = { id = "org.jetbrains.kotlin.android", version = "1.9.0" }
jetbrains-dokka = { id = "org.jetbrains.dokka", version = "1.9.20" }
vanniktech-maven-publish = { id = "com.vanniktech.maven.publish", version = "0.28.0" }
