site_name: Scale
theme: material

nav:
  - Overview: overview.md
  - ZoomableView: zoomable_view.md
  - ZoomableView State and Gesture: zoomable_state.md
  - ZoomablePager: zoomable_pager.md
  - ZoomablePager State and Gesture: zoomable_pager_state.md