name: Smart Module Publishing

on:
  push:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: ['scale-image-viewer', 'scale-zoomable-view']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Publish ${{ matrix.module }}
        run: ./gradlew :${{ matrix.module }}:publish
        env:
          GITHUB_PACKAGE_USER: ${{ github.actor }}
          GITHUB_PACKAGE_TOKEN: ${{ secrets.TOKEN }}